<a href="https://colab.research.google.com/github/Anbusasi-89/Python/blob/main/Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Students Marks Analysis
import numpy as np
Marks = np.array([60,72,85,90,77,69,88,91]) #Array
Avg = np.mean(Marks)
print("Average Mark: ", Avg)
Count = 0
for Mark in Marks:
  if Mark > 80:
    Count += 1
print("No of Students who scored above 80:", Count)
min_mark = Marks.min()
max_mark = Marks.max()
difference = max_mark - min_mark
print("Difference between min and max marks:",difference)

Average Mark:  79.0
No of Students who scored above 80: 4
Difference between min and max marks: 31


In [ ]:
# Sales Data Analysis
import numpy as np
DailySales = np.array([12.5,10.2,9.8,14.6,13.3,15.0,11.9])
Days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
TotalSales = np.sum(DailySales)
print(f"Total Sales for the week: {TotalSales:.2f}") #f represents formatted string
AvgSales = np.average(DailySales)
print(f"Average Daily Sales: {AvgSales:.2f}")
#above_avg_days = [Days[i] for i in range(len(DailySales)) if DailySales[i] > AvgSales]
print("Days when sales greater than Average:")
for i in range(len(DailySales)):
  if DailySales[i] > AvgSales:
    i += 1
    print(Days[i])
#print("Days when Sales greater than Average:", above_avg_days)

Total Sales for the week: 87.30
Average Daily Sales: 12.47
Days when sales greater than Average:
Tuesday
Friday
Saturday
Sunday


In [ ]:
#Temperature Conversion
import numpy as np
celsius = np.array([34,30,28,35,33,29])
fahrenheit = (celsius * 9/5) + 32
print("Fahrenheit:",fahrenheit)

Fahrenheit: [93.2 86.  82.4 95.  91.4 84.2]


In [ ]:
#Product Price Increase
import numpy as np
prices = np.array([120,250,89,300,150])
#increase all prices by 10%
increased_prices = prices * 1.10
#Find new average price
average_price = np.mean(increased_prices)
#Find products that are no above 250
above_250 = increased_prices[increased_prices>250]
print("Increased Prices:", increased_prices)
print("New Average Price:", average_price)
print("Products above Rs.250:", above_250)

Increased Prices: [132.  275.   97.9 330.  165. ]
New Average Price: 199.98
Products above Rs.250: [275. 330.]


In [ ]:
#Matrix Addition
import numpy as np
class1 = np.array([[70,85,90],[60,75,80]])
class2 = np.array([[65,88,92],[58,72,79]])
total_marks = class1 + class2
average_per_student = np.mean(total_marks,axis=0)
print("Total Marks:\n", total_marks)
print("Average Score per Student:", average_per_student)

Total Marks:
 [[135 173 182]
 [118 147 159]]
Average Score per Student: [126.5 160.  170.5]


In [6]:
#Numpy Practice Exercise
import numpy as np
#1. Create a Numpy array of numbers from 1 to 11
array1 = np.arange(1,11)
print("Array from 1 to 11:", array1)
#2. Create a 2x3 array filled with zeros
zeros_array = np.zeros((2,3))
print("\n2x3 array of zeroes\n",zeros_array)
#3. Generate an array of 5 equally spaced values between 0 and 1
linspaced_array = np.linspace(0,1,5)
print("\n5 equally spaced values between 0 and 1:",linspaced_array)
#4. Extract the even numbers from an array and multiple by 10
a = np.array([1,2,3,4,5])
even_numbers = a[a % 2 == 0]
print("\nEven Numbers:", even_numbers)
multiplied = a * 10
print("\nEach element multipled by 10:",multiplied)
#5.Reshape an array of shape(6,) to shape(2,3)
reshape_arr = np.array([1,2,3,4,5,6])
reshaped = reshape_arr.reshape(2,3)
print("\nReshaped (2,3) array:\n",reshaped)
#6.compute the sum and mean of an array
sum_value = reshape_arr.sum()
mean_value = reshape_arr.mean()
print("\nSum:",sum_value)
print("\nMean:",mean_value)

Array from 1 to 11: [ 1  2  3  4  5  6  7  8  9 10]

2x3 array of zeroes
 [[0. 0. 0.]
 [0. 0. 0.]]

5 equally spaced values between 0 and 1: [0.   0.25 0.5  0.75 1.  ]

Even Numbers: [2 4]

Each element multipled by 10: [10 20 30 40 50]

Reshaped (2,3) array:
 [[1 2 3]
 [4 5 6]]

Sum: 21

Mean: 3.5
